name: docker-self-hosted
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  
env:
  VERSION_TAG: $(date +%s)

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:${{ env.VERSION_TAG }}

  test:
    runs-on: self-hosted
    needs: [build]
    services: 
      server: 
        image: redis
    steps:
      - uses: actions/checkout@v3
