name: docker-self-hosted
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  
env:
  PR_NUMBER: ${{ github.event.pull_request.number }}

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag myapp:${{ env.PR_NUMBER }}

  deploy:
    runs-on: self-hosted
    needs: [build]
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to k8
        run: sh ./k8/app-deployment.sh
