name: test
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)

  build-and-publish-latest:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' # Running this job only for master branch

    steps:
        - uses: actions/checkout@v2 # Checking out the repo

        - name: Build and Publish latest Docker image
          uses: VaultVulp/gp-docker-action@1.6.0
          with:
              github-token: ${{ secrets.GITHUB_TOKEN }} # Provide GITHUB_TOKEN to login into the GitHub Packages
              image-name: my-cool-service # Provide only Docker image name, tag will be automatically set to latest
              dockerfile: Dockerfile_server